language: node_js
node_js:
- node
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
before_script:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules
env:
  global:
    secure: SFHel2f0ZSEGPtkFvp8t+iqAu8C21ZmGyK/L1Ru+wBzEo/FnqIxnTq5fFEbODaHnlHJqdBKIQqVjr8EtUMToPPEVCdPbTzP5U7c4h2wlYPcf6MXDblv4jfNNdHOxtyc2IDWtoT9wI6byj1QyBWCqwtk1vbycKcsH+PFJ1xyEUh4KmPkf2vi8FC8FmIPgqyOXkDHazPX6G1+CsKZU4MItVZeZzcOJ/coB/96Gg8vZ1vLWpWBcIWvsM703ugmSLyJa841E7oi3vDMDvLN7GxVstyZ7T2tw4d/nhfuM6wNVt3oNsdsdtKUwZp0tr42kIzRYgDTVK/02aDYjA4hLeLth1filW+9VFTAUVKpwxBXp91GO8gLfaYKR1cTDd0zxsfKuthTGVtcwUoQGxIZKqRLQwA5tf2ZEKCHEfpRzbJa2nHEllHAcB9CDapEYQLG4l/BFLQuRItc6+RFxJpovXH6iL8nSzUHNvXQP9mHt3VMjLQPFvkc3YhK5HSO7q7L92v2O1maAsMHFmPhELxm2B+3FaVqFtU9eZ2iAspHDIn+Bu4C2kidebcFwvK40YCdBJE65goSCT+4lbXIHsQSfRPFVdX9xaj4wHJ3+se2bV/6wAyFEXy/1RroU69h6VYtfDWsIcPT37D75T3infs6qIL25bdTTCbiy1BsBhMJgP8b5Alw=
